# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: Bash@3
    displayName: "Show variables"
    inputs:
      targetType: 'inline'
      script: |
        echo "Build.SourcesDirectory - $(Build.SourcesDirectory)"
        echo "Agent.BuildDirectory - $(Agent.BuildDirectory)"
        echo "Build.BinariesDirectory - $(Build.BinariesDirectory)"
        echo "Build.ArtifactStagingDirectory - $(Build.ArtifactStagingDirectory)"
        echo "Common.TestResultsDirectory - $(Common.TestResultsDirectory)"
    
